inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/**/*.rb'

RSpec/NamedSubject:
  Enabled: false

Documentation:
  Enabled: false
