inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
  - 'Rakefile'
  - '**/*.rake'
  - 'spec/**/*.rb'

Documentation:
  Enabled: false

EnforcedStyle: expanded