# Copy and set environment variable values in a new environment_variables.yml

development:
  GIT_REPOSITORY_URL: GIT_REPOSITORY_URL
  GIT_REPOSITORY_NAME: GIT_REPOSITORY_NAME
  GITHUB_USER_NAME: GITHUB_USER_NAME
  GITHUB_USER_EMAIL: GITHUB_USER_EMAIL
  VSPHERE_SERVER_IP: '127.0.0.1'
  VSPHERE_SERVER_USER: 'email@email.com'
  VSPHERE_SERVER_PASSWORD: 'password'

production:
  GIT_REPOSITORY_URL: GIT_REPOSITORY_URL
  GIT_REPOSITORY_NAME: GIT_REPOSITORY_NAME
  GITHUB_USER_NAME: GITHUB_USER_NAME
  GITHUB_USER_EMAIL: GITHUB_USER_EMAIL
  VSPHERE_SERVER_IP: '127.0.0.1'
  VSPHERE_SERVER_USER: 'email@email.com'
  VSPHERE_SERVER_PASSWORD: 'password'

test:
  GIT_REPOSITORY_URL: test_repository_url
  GIT_REPOSITORY_NAME: test_repository_name
  GITHUB_USER_NAME: test_user_name
  GITHUB_USER_EMAIL: test_user_email