# Copy and set environment variable values in a new environment_variables.yml

development:
  GIT_REPOSITORY_URL: GIT_REPOSITORY_URL
  GIT_REPOSITORY_NAME: GIT_REPOSITORY_NAME
  GITHUB_USER_NAME: GITHUB_USER_NAME
  GITHUB_USER_EMAIL: GITHUB_USER_EMAIL
production:
  GIT_REPOSITORY_URL: GIT_REPOSITORY_URL
  GIT_REPOSITORY_NAME: GIT_REPOSITORY_NAME
  GITHUB_USER_NAME: GITHUB_USER_NAME
  GITHUB_USER_EMAIL: GITHUB_USER_EMAIL